### PR TITLE
add async client

### PR DESCRIPTION
**Pull request by akhilputhiry**
To incorporate ideas from https://github.com/keycloak-client/keycloak-client/pull/69

### CODE REVIEW

**Comment by akhilputhiry** [comment]
Hi @PWRScript

I have made some changes on top of your PR. Could you please take a look.

**Review by PWRScript — CHANGES_REQUESTED** [review]
Good night @akhilputhiry,

Thanks for considering my suggestion to add async support to this library and for reviewing my PR.
Your PR looks good and the httpx depedency is very promising as it removes the need for 2 libraries and "joins" the codebase, making it easier to port the sync code to async code
i have looked to your modifications and I added a comment to the issues that I have found in your code.
After these corrections we could look foward to finish the Quart extension integration, make the CI build successfuly again and finally release the new version of the keycloak-client

Thanks for your time and Best Regards,
Miguel

**Review by PWRScript — CHANGES_REQUESTED** [review]
Good night @akhilputhiry, I have looked to your new commit and made some corretions/suggestions to fix the core code and the quart extension which used code from the «first version» of the PR. If you didn´t mind, could you review the commit and fix the problems

Also, when I was testing the async version of the library, I have optimized the quart example which I will send the code to insert in the examples

```py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from quart import Quart
from quart.globals import session
from keycloak.extensions.quart import AuthenticationMiddleware, login_required

app = Quart(__name__)
app.secret_key = "secret0123456789"

AuthenticationMiddleware(
    app,
    callback_url="http://localhost:5000/kc/callback",
    login_redirect_uri="/home",
    logout_redirect_uri="/logout",
)

@app.route("/home")
@login_required(force_login_redirect=True)
async def home():
    user = session["user"]
    return f'Howdy {user} <a href="/kc/logout">Logout</a>'

@app.route("/logout")
async def logout():
    return 'User logged out successfully <a href="/">Login again</a>'


if __name__ == '__main__':
    app.run(port=5000) 
```

As we are now almost close to finish the async implementation, I have to say that I'm pleasing of working with you to improve your library and also thank you for your time and helpness.

Best Regards,
Miguel

**Comment by akhilputhiry** [comment]
Thank you @PWRScript 

I was trying to convert the quart extension as a proper middleware as described [here](https://pgjones.gitlab.io/quart/how_to_guides/middleware.html)

**Comment by PWRScript** [comment]
@akhilputhiry first I have tried to write the ASGI middleware but I found some problems during that (session saving not working which leaded to invalid states during callback, custom responses requiring callable, ...) so I wrote a extension.
When you commit the middleware I will look into it to see how it works and where I failed
Good work with it and thanks for your time

**Comment by akhilputhiry** [comment]
Hi @PWRScript 

I need some time to finish quart extension properly.
I will merge the async client now, so that you can just have the quart middleware inside your application and proceed.

Thank you for your contributions

**Comment by PWRScript** [comment]
@akhilputhiry Thanks for adding the async support
For now I will integrate with keycloak using the extension that I developed and the new code implemented in keycloak-client
I will continue to look for this repository and if I have more suggestions or features to implement I will contact you
Thanks for ypur time and good luck, Miguel

**Pull request merged**
